-- MySQL Script generated by MySQL Workbench
-- 04/29/14 20:53:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ProjetoCadCurriculoBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoCadCurriculoBD` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ProjetoCadCurriculoBD` ;

-- -----------------------------------------------------
-- Table `ProjetoCadCurriculoBD`.`Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoCadCurriculoBD`.`Candidato` (
  `id_candidato` INT NOT NULL IDENTITY(1,1),
  `nome_candidato` VARCHAR(255) NOT NULL,
  `email_candidato` VARCHAR(100) NOT NULL,
  `senha_candidato` VARCHAR(45) NOT NULL,
  `data_nasc_candidato` DATE NULL,
  `cpf_candidato` VARCHAR(14) NULL,
  `end_candidato` VARCHAR(255) NULL,
  `telefone_candidato` VARCHAR(16) NULL,
  `escolaridade_candidato` INT NOT NULL,
  `exp_candidato` VARCHAR(500) NULL,
  `area_atuacao_candidato` VARCHAR(255) NULL,
  `apendices_candidato` VARCHAR(500) NULL,
  PRIMARY KEY (`id_candidato`, `email_candidato`),
  UNIQUE INDEX `id_candidato_UNIQUE` (`id_candidato` ASC),
  UNIQUE INDEX `email_candidato_UNIQUE` (`email_candidato` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoCadCurriculoBD`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoCadCurriculoBD`.`Empresa` (
  `id_empresa` INT NOT NULL IDENTITY(1,1),
  `nome_empresa` VARCHAR(255) NOT NULL,
  `email_empresa` VARCHAR(255) NOT NULL,
  `senha_empresa` VARCHAR(45) NOT NULL,
  `cnpj_empresa` VARCHAR(16) NULL,
  `telefone_empresa` VARCHAR(16) NULL,
  `end_empresa` VARCHAR(255) NULL,
  PRIMARY KEY (`id_empresa`, `email_empresa`),
  UNIQUE INDEX `id_empresa_UNIQUE` (`id_empresa` ASC),
  UNIQUE INDEX `email_empresa_UNIQUE` (`email_empresa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoCadCurriculoBD`.`Vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoCadCurriculoBD`.`Vaga` (
  `id_vaga` INT NOT NULL,
  `carga_horaria_vaga` INT NOT NULL,
  `remuneracao_vaga` DECIMAL(10,2) NOT NULL,
  `requisitos_vaga` VARCHAR(500) NOT NULL,
  `desc_vaga` VARCHAR(500) NOT NULL,
  `Empresa_id_empresa` INT NOT NULL,
  `Empresa_email_empresa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_vaga`, `Empresa_id_empresa`, `Empresa_email_empresa`),
  UNIQUE INDEX `id_vaga_UNIQUE` (`id_vaga` ASC),
  INDEX `fk_Vaga_Empresa_idx` (`Empresa_id_empresa` ASC, `Empresa_email_empresa` ASC),
  CONSTRAINT `fk_Vaga_Empresa`
    FOREIGN KEY (`Empresa_id_empresa` , `Empresa_email_empresa`)
    REFERENCES `ProjetoCadCurriculoBD`.`Empresa` (`id_empresa` , `email_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoCadCurriculoBD`.`Candidato_has_Vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoCadCurriculoBD`.`Candidato_has_Vaga` (
  `Candidato_id_candidato` INT NOT NULL,
  `Candidato_email_candidato` VARCHAR(100) NOT NULL,
  `Vaga_id_vaga` INT NOT NULL,
  `Vaga_Empresa_id_empresa` INT NOT NULL,
  `Vaga_Empresa_email_empresa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Candidato_id_candidato`, `Candidato_email_candidato`, `Vaga_id_vaga`, `Vaga_Empresa_id_empresa`, `Vaga_Empresa_email_empresa`),
  INDEX `fk_Candidato_has_Vaga_Vaga1_idx` (`Vaga_id_vaga` ASC, `Vaga_Empresa_id_empresa` ASC, `Vaga_Empresa_email_empresa` ASC),
  INDEX `fk_Candidato_has_Vaga_Candidato1_idx` (`Candidato_id_candidato` ASC, `Candidato_email_candidato` ASC),
  CONSTRAINT `fk_Candidato_has_Vaga_Candidato1`
    FOREIGN KEY (`Candidato_id_candidato` , `Candidato_email_candidato`)
    REFERENCES `ProjetoCadCurriculoBD`.`Candidato` (`id_candidato` , `email_candidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidato_has_Vaga_Vaga1`
    FOREIGN KEY (`Vaga_id_vaga` , `Vaga_Empresa_id_empresa` , `Vaga_Empresa_email_empresa`)
    REFERENCES `ProjetoCadCurriculoBD`.`Vaga` (`id_vaga` , `Empresa_id_empresa` , `Empresa_email_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
